### ISSUE TITLE
the run method in Counter class will  never be stop

### ISSUE THREAD

**Issue by ervinsae** [premnirmal/TextCounter#1]
the thread of counter will always run ,because the valuesAreCorrect() method in Counnter class is always true

**Comment by premnirmal** [comment]
Agreed, I'll add a check to see if the value is the endValue, and if it is, no longer post the runnable

**Comment by premnirmal** [comment]
Thanks for the feedback

**Comment by DonManfred** [comment]
any news on this?

**Comment by premnirmal** [comment]
@DonManfred I think the bug is here https://github.com/premnirmal/TextCounter/blob/master/TextCounter/src/main/java/com/github/premnirmal/textcounter/Counter.java#L46. Haven't gone round to fixing and publishing yet, but if you are using by source you can simply remove the 'equals' part from that line

**Comment by DonManfred** [comment]
@premnirmal Thank you for your answer. :+1: 
I´m using the jar-Version. So i guess i should wait for the next release :-)
Best regards, Manfred

**Comment by premnirmal** [comment]
@DonManfred release will be in the next day or two. Thanks for waiting

**Comment by DonManfred** [comment]
@premnirmal No problem... 
I´m using Basic4Android and have written a wrapper to be able to use your lib in BasicAndroid (http://www.b4x.com/b4a.html). I have not released the wrapper actually. Will do this after the new release is avilable.

**Comment by premnirmal** [comment]
@DonManfred version 1.1.0 should be on its way to maven central. give it a few hours to upload
